cypress-io/cypress-design

- .changeset/eight-cobras-mix.md
- components/Button/constants.ts
- components/Button/react/Button.tsx
- components/Button/vue/Button.vue
This PR adds the following changes:
- Minor updates to the button styles to match closer with Figma
- Added a new button style that would get used in the marketing website
> Button Updates

- .changeset/serious-kiwis-matter.md
- components/Alert/react/Alert.module.scss
- components/Alert/react/Alert.tsx
- components/Alert/vue/Alert.vue
Add animation on the details marker when details open and close.
https://user-images.githubusercontent.com/5592465/180088716-6762aecf-31da-4173-875a-27882c17219f.mp4
> feat: animate transition of details caret

- storybook/intro/stories/intro/5-Icons.stories.mdx
Just a super basic search for now
> Add a search input for icons

- .changeset/twelve-pens-jog.md
- css/package.json
- css/src/get-config.test.ts
- css/src/get-config.ts
- css/src/icon-color-plugins.ts
- css/src/index.ts
- css/src/windi.config.ts
- css/tsconfig.build.json
- astro files need to be scanned by the icon plugin
- `lodash.merge` does not merge array at all (added unit tests to make sure)
- We do not need to published compiled tests
> feat: css another round of fixes

- .changeset/big-dolphins-occur.md
- components/checkbox/react/Checkbox.tsx
- components/checkbox/react/CheckboxReact.cy.tsx
- components/checkbox/vue/Checkbox.vue
- components/checkbox/vue/CheckboxVue.cy.tsx
instead of only on the label.
See https://design.cypress.io/?path=/docs/react_checkbox--checkbox
> fix: make the checkbox change state when you click

- .changeset/plenty-planets-explode.md
- components/Button/assertions.ts
- components/Button/constants.ts
- components/Button/react/Button.rootstory.tsx
- components/Button/react/Button.stories.mdx
- components/Button/react/Button.tsx
- components/Button/react/ButtonReact.cy.tsx
- components/Button/react/tsconfig.json
- components/Button/vue/Button.rootstory.tsx
- components/Button/vue/Button.stories.mdx
- components/Button/vue/Button.ts
- components/Button/vue/ButtonVue.cy.tsx
- components/Button/vue/tsconfig.json
- components/Tooltip/assertions.ts
> feat: add href prop to button

- components/Accordion/assertions.ts
- components/Accordion/constants.ts
- components/Accordion/react/Accordion.rootstory.tsx
- components/Accordion/react/Accordion.stories.mdx
- components/Accordion/react/Accordion.tsx
- components/Accordion/react/AccordionReact.cy.tsx
- components/Accordion/vue/Accordion.rootstory.tsx
- components/Accordion/vue/Accordion.stories.mdx
- components/Accordion/vue/Accordion.vue
- components/Accordion/vue/AccordionVue.cy.tsx
- test/vue-app/src/App.vue
> [DESIGN-1263] Allow Accordion to be passed an image element

- .changeset/long-planes-rhyme.md
- .vscode/settings.json
- components/Tooltip/react/Tooltip.tsx
- components/Tooltip/vue/Tooltip.vue
- components/Tooltip/vue/TooltipVue.cy.tsx
Fix this issue https://github.com/cypress-io/cypress.io/issues/247
> fix: avoid blinky tooltips

- .changeset/light-cooks-guess.md
- icon-registry/icons/object-tassel_x16.svg
> feat: add tassel icon

- docs/.vitepress/theme/components/EditButton.vue
- docs/.vitepress/theme/components/Layout.vue
- docs/.vitepress/theme/components/SideBar.vue
- docs/.vitepress/theme/components/markdown.scss
- docs/.vitepress/theme/utils/docsPages.ts
> docs: improvements

- docs/.vitepress/theme/components/Layout.vue
- docs/.vitepress/theme/components/markdown.scss
- docs/docgen/docgen.config.cjs
- docs/docgen/docgen.config.vue.cjs
- docs/docgen/docgen.template.events.cjs
- docs/docgen/docgen.template.props.cjs
- docs/docgen/docgen.template.slots.cjs
- docs/docgen/renderType.cjs
add slot & events extra information
> Docgen improve

- .changeset/reactive-props.md
- components/Button/vue/Button.vue
- components/Button/vue/ButtonVue.cy.tsx
- cypress/support/commands.ts
- package.json
- yarn.lock
> fix: prop button reactivity

- .changeset/branch-review-icons.md
- icon-registry/icons/arrow-bottom-right_x16.svg
- icon-registry/icons/arrow-top-right_x16.svg
- icon-registry/icons/document-added-square-plus_x16.svg
- icon-registry/icons/document-added-square-plus_x24.svg
- icon-registry/icons/document-modified-square-dot_x16.svg
- icon-registry/icons/document-modified-square-dot_x24.svg
- icon-registry/icons/status-flaky_x16.svg
- icon-registry/icons/status-flaky_x24.svg
Icon names were derived from the design system's descriptions, I'm happy to update these as needed.
> Adding icons for branch review 

- .changeset/multi-checkbox-vue.md
- components/Checkbox/vue/Checkbox.rootstory.tsx
- components/Checkbox/vue/Checkbox.vue
- components/Checkbox/vue/CheckboxVue.cy.tsx
- docs/docgen/renderType.cjs
> checkbox: work with array v-model

- .changeset/data-pendo-prop-for-tab.md
- components/Tabs/assertions.ts
- components/Tabs/constants/src/index.ts
- components/Tabs/react/Tabs.tsx
- components/Tabs/react/TabsReact.cy.tsx
- components/Tabs/vue/Tabs.vue
- components/Tabs/vue/TabsVue.cy.tsx
The Cypress Cloud is using tabs and needs pendo tags to track events in full story and pendo
> Allow Tab to accept data-pendo prop

- .changeset/tabs-custom-render.md
- components/Tabs/constants/src/index.ts
- components/Tabs/react/Tabs.tsx
- components/Tabs/react/TabsReact.cy.tsx
- components/Tabs/vue/Tabs.vue
- components/Tabs/vue/TabsVue.cy.tsx
> feat: allow passing nodes to tab labels

- .changeset/odd-badgers-add.md
- components/DocMenu/ReadMe.md
- components/DocMenu/assertions.ts
- components/DocMenu/constants/src/index.ts
- components/DocMenu/react/DocMenu.tsx
- components/DocMenu/react/DocMenuReact.cy.tsx
- components/DocMenu/react/ReadMe.md
- components/DocMenu/react/_DocGroup.tsx
- components/DocMenu/react/_DocLink.tsx
- components/DocMenu/vue/DocMenu.vue
- components/DocMenu/vue/DocMenuVue.cy.tsx
- components/DocMenu/vue/ReadMe.md
- components/DocMenu/vue/_DocGroup.vue
- components/DocMenu/vue/_DocGroupElements.vue
- components/DocMenu/vue/_DocLink.vue
- docs/.vitepress/config.ts
- docs/.vitepress/theme/components/DocsOutline.vue
- docs/.vitepress/theme/components/EditButton.vue
- docs/.vitepress/theme/components/SideBar.vue
- docs/.vitepress/theme/utils/docsPages.ts
- test/react-app/src/App.tsx
> feat: work on marker placement and movement

- .changeset/tooltip-deps-update.md
- components/Modal/react/Modal.tsx
- components/Tooltip/react/ReadMe.md
- components/Tooltip/react/Tooltip.tsx
- components/Tooltip/react/TooltipReact.cy.tsx
- components/Tooltip/react/package.json
- yarn.lock
[Status] right now, the built version of this component errors in the built documentation. "Under investigation". until I know more, we should avoid updating.
> tooltip: use the not-deprecated library

- .changeset/spotty-coins-trade.md
- icon-registry/icons/object-pin-modern_x12.svg
> Added pin icon x12

- .changeset/early-files-change.md
- ReadMe.md
- icon-registry/icons-static/social-twitter-x-solid_x16.svg
> Add Twitter X icon

- .changeset/thick-wolves-peel.md
- icon-registry/icons-static/action-upgrade-square_x16.svg
> Add icon upgrade square

- .changeset/seven-jokes-cross.md
- icon-registry/icons-static/technology-git-commit_x16.svg
> Add git commit icon

- .changeset/calm-onions-shop.md
- components/Button/constants/src/index.ts
Reference in Figma design system: https://www.figma.com/design/1WJ3GVQyMV5e7xVxPg3yID/Design-System?node-id=18922-62234&t=QrUgMCg08KAsKkJX-4
> Adding tertiary button

- .changeset/quick-jokes-dream.md
- icon-registry/icons-static/shape-flag_x16.svg
> Add flag icon

- .changeset/strong-cycles-cheer.md
- icon-registry/icons-static/object-stack-failed_x16.svg
- icon-registry/icons-static/object-stack-passed_x16.svg
- icon-registry/icons-static/object-stack-queued_x16.svg
- icon-registry/icons-static/object-stack-running_x16.svg
[Figma](https://www.figma.com/design/1WJ3GVQyMV5e7xVxPg3yID/Design-System?m=auto&node-id=6814-10841&t=Fzv96ihRShr3q9ZQ-1)
> feat: add object stack icons

- .changeset/vast-ties-slide.md
- components/Menu/react/Menu.tsx
- components/Menu/vue/_MenuItem.vue
Add transient active state to MenuItem to trigger animated icon on press
> Add transient active to menu

- .github/workflows/e2e-tests.yml
- .github/workflows/test.yml
Didn't copy the correct dist folder to all cache jobs
> copy details-animation/dist

- .changeset/fair-sites-behave.md
- icon-registry/icons-static/technology-dashboard-fail_x24.svg
related to https://github.com/cypress-io/cypress-services/issues/10387
> add technology-dashboard-fail 24px for studio
