cypress-io/cypress-design

.changeset/proud-ways-dance.md
components/Alert/react/Alert.module.scss
components/Alert/react/Alert.tsx
components/Alert/react/css-modules.d.ts
components/Alert/react/package.json
components/Alert/react/rollup.config.js
components/Alert/react/tsconfig.build.json
components/Alert/vue/Alert.rootstory.tsx
components/Alert/vue/Alert.stories.mdx
components/Alert/vue/Alert.vue

The alert stories do not open for vue
https://design.cypress.io/?path=/story/vue_alert--alert
On react we have double icons on safari
https://design.cypress.io/?path=/story/react_alert--alert

fix: alert stories + double alert details caret

---

.changeset/orange-jars-sin.md
components/Alert/react/package.json
components/Alert/vue/package.json
components/Button/react/package.json
components/Button/vue/package.json
components/Spinner/react/package.json
components/Spinner/vue/package.json
components/StatusIcon/react/package.json
components/StatusIcon/vue/package.json
components/Tooltip/react/package.json
components/Tooltip/vue/package.json
components/checkbox/react/package.json
components/checkbox/vue/package.json
components/icon/react/package.json
components/icon/vue/Icon.ts
components/icon/vue/package.json
components/root.rollup.config.js
components/root.vite.config.ts
icon-registry/package.json
icon-registry/rollup.config.js
icon-registry/src/compileIcon.ts
icon-registry/tsconfig.json
package.json
storybook/intro/.storybook/main.js
storybook/react/.storybook/main.js
test/vue-app/package.json
yarn.lock

Astro is a bit more stringent than just vite since it is doing SSG and SSR.
It needs all modules/components to work on both node and in the browser.
ESM does not work natively in node. 
We have to rename the files `.mjs` to make it work.

feat: create dot mjs files for esm

---

_templates/component/new/components_ComponentName_assertions.ts.ejs.t
_templates/component/new/components_ComponentName_constants.ts.ejs.t
_templates/component/new/components_ComponentName_react_ComponentName.cy.tsx.ejs.t
_templates/component/new/components_ComponentName_react_ComponentName.rootstory.tsx.ejs.t
_templates/component/new/components_ComponentName_react_ComponentName.tsx.ejs.t
_templates/component/new/components_ComponentName_react_package.json.ejs.t
_templates/component/new/components_ComponentName_react_tsconfig.build.json.ejs.t
_templates/component/new/components_ComponentName_react_tsconfig.json.ejs.t
_templates/component/new/components_ComponentName_vue_ComponentName.cy.tsx.ejs.t
_templates/component/new/components_ComponentName_vue_ComponentName.rootstory.tsx.ejs.t
_templates/component/new/components_ComponentName_vue_ComponentName.vue.ejs.t
_templates/component/new/components_ComponentName_vue_package.json.ejs.t
_templates/component/new/components_ComponentName_vue_tsconfig.build.json.ejs.t
_templates/component/new/components_ComponentName_vue_tsconfig.json.ejs.t
components/Alert/vue/package.json
components/root.vite.config.ts
package.json
yarn.lock

Make sharable constants a default for cypress components.
This change is only done for templates used by `yarn new:component`
It also shares cypress assertions by default so we run tests on both vue and react

feat: shared constants

---

.changeset/olive-mice-promise.md
components/StatusIcon/react/package.json
components/StatusIcon/vue/package.json

I'm hoping this will fix [this build failure](https://app.circleci.com/pipelines/github/cypress-io/cypress-services/21895/workflows/8435a646-b9b2-43bc-96e0-6111bfe18c7a/jobs/312072), although i'm not sure...

Fix status icons types file location

---

.changeset/remove-svg-prefix-on-classes.md
icon-registry/svgo.config.js

> We spoke too soon.  The change you made also prefixed all the class names, so the icons that rely on having classess like icon-dark or icon-light now look like long_prefx_icon_name_icon-dark instead.  It looks like the built in plugin you used (“prefixIds”) has an undocumented parameter called prefixClassNames that you can set to false.  See code here: https://github.com/svg/svgo/blob/main/plugins/prefixIds.js#L76
Fix this and re-release

fix: remove prefix on svg classes

---

.changeset/new-tabs-feat.md
components/Tabs/ReadMe.md
components/Tabs/constants.ts
components/Tabs/react/ReadMe.md
components/Tabs/react/Tabs.tsx
components/Tabs/vue/ReadMe.md
components/Tabs/vue/Tabs.vue
docs/.vitepress/theme/components/markdown.scss

fix: better tabs

---

.changeset/dark-tabs-variants.md
components/Tabs/ReadMe.md
components/Tabs/assertions.ts
components/Tabs/constants/package.json
components/Tabs/constants/src/index.ts
components/Tabs/react/ReadMe.md
components/Tabs/react/Tabs.rootstory.tsx
components/Tabs/react/Tabs.tsx
components/Tabs/react/TabsReact.cy.tsx
components/Tabs/vue/Tabs.rootstory.tsx
components/Tabs/vue/Tabs.vue
components/Tabs/vue/TabsVue.cy.tsx

closes #212
In the scope of Test Replay initiative we're introducing dark version of the tabs component in two different sizes.
References:
- [Figma design](https://www.figma.com/file/1WJ3GVQyMV5e7xVxPg3yID/Design-System%2C-v1.x---%40latest?node-id=12760-26631&t=lFqizbY9YMDhx8vi-4)
- [Slack thread](https://cypressio.slack.com/archives/C3WD9SGKW/p1682970681920569)

Dark mode tabs

---

.changeset/forceopen-prop.md
.changeset/no-portal-empty-div.md
.github/workflows/test.yml
components/Modal/react/Modal.tsx
components/Tooltip/react/Tooltip.tsx
components/Tooltip/react/TooltipReact.cy.tsx
components/Tooltip/vue/Tooltip.vue
components/Tooltip/vue/TooltipVue.cy.tsx
package.json
test/react-app/index.html
test/react-app/package.json
test/react-app/src/App.tsx
yarn.lock

closes #263
closes #260 
also add forceOpen for development and design

Stop Tooltip component from creating empty div

---

docs/.vitepress/theme/components/Layout.vue

Small issue with layout on the XL breakpoint around 1300px wide.
Before: 
After:

Remove xl breakpoint on main

---

components/Tabs/react/ReadMe.md

The ReadMe for tabs was at odds with the implementation. This PR fixes it :)

fix: use activeId in tabs readme

---

.changeset/fast-geckos-taste.md
icon-registry/icons/device-tv_x16.svg
icon-registry/icons/device-tv_x24.svg

Add the Device TV icon from the Figma Design System.

Add the Device TV icon

---

.changeset/rare-boats-talk.md
components/Button/vue/ButtonVue.cy.tsx
cypress.config.ts
icon-registry/icons/action-delete-small_x16.svg
icon-registry/icons/action-delete-xsmall_x16.svg
icon-registry/icons/checkmark-solid_x16.svg
icon-registry/icons/checkmark-solid_x24.svg
yarn.lock

Icon Improvements: ActionDelete & CheckmarkSolid

---

.changeset/tab-ariaControls.md
components/Button/react/index.ts
components/Button/vue/index.ts
components/Tabs/ReadMe.md
components/Tabs/assertions.ts
components/Tabs/constants/package.json
components/Tabs/constants/src/index.ts
components/Tabs/react/ReadMe.md
components/Tabs/react/Tabs.tsx
components/Tabs/react/TabsReact.cy.tsx
components/Tabs/vue/ReadMe.md
components/Tabs/vue/Tabs.vue
components/Tabs/vue/TabsVue.cy.tsx
docs/.vitepress/theme/components/FrameworkSwitch.vue
docs/.vitepress/theme/components/Layout.vue
test/react-app/src/App.tsx

Tabs component:
- `aria-controls` is required for each tab
- `aria-selected` was `undefined` when false; now it is set to `false` 
- Existing `id` prop on the Tab is also now propagated as an attribute 
Buttons component: 
- Exports StaticClasses

fix: make tabs component more accessible, export button staticclasses

---

.changeset/curvy-mayflies-tell.md

Forgot to bump the icon package versions in #476 so that I can use the new icon in cypress-services.

bump icon packages

---

.changeset/mighty-snakes-thank.md
icon-registry/icons-static/document-square-minus_x12.svg
icon-registry/icons-static/square-minus_x12.svg
icon-registry/icons-static/square-minus_x16.svg
icon-registry/icons-static/square-minus_x24.svg

Adding icon as seen in Figma here: https://www.figma.com/design/zVWa3fJtO0EWZ5FEhqtCRL/Branch-Review%2C-v1.1---%40latest?t=xcmiNHxq0O0NXmJc-0
Wasn't sure if bundling the red color by default would be expected/desirable - happy to tweak this if so.

Adding square-minus icons

---

.changeset/great-toes-beg.md

Button constants updates form the last version was not release with the last button release.
To replicate this issue, install the latest `@cypress-design/react-button` and try using the `outline-red` variant on a button. You will see a typescript typing error.

fix: update button constants for button

---

.changeset/metal-hotels-learn.md
.changeset/rotten-gifts-refuse.md
components/Button/constants/src/index.ts

Adding outline-orange-dark and outline-orange-light buttons

---

components/Button/react/ReadMe.md
components/Button/vue/ReadMe.md

I couldn't figure out why the types were not being picked up properly for my react-buttons component. It turns out those types are being pulled in from the constants-button dependency and if you don't have that package also installed - it just cannot access it. 
This updates the instructions to tell you to install the constants-button package also and why you'd want it installed.

docs: Update the button component install instructions

---

.changeset/clean-plants-change.md
components/Button/constants/src/index.ts
components/Button/react/Button.rootstory.tsx
components/Button/react/ReadMe.md
components/Button/vue/Button.rootstory.tsx
components/Button/vue/ReadMe.md

Preview:
Buttons are previewed on a dark background which indicates that they are dark mode buttons.
Currently we're adding these buttons as new button variants.
In the future we will introduce prop `theme` with values inherit, light and dark. This will enable us to decrease number of variants, but will also require refactoring.

Adding red-dark-mode and outline-red-dark-mode buttons

---

.changeset/famous-cups-nail.md
components/Button/constants/src/index.ts
components/Button/react/ReadMe.md

Updating disabled states for buttons: outline-indigo, outline-purple, outline-red, outline-gray-dark, outline-orange-dark, outline-orange-light
outline-indigo
outline-red
outline-gray-dark
outline-orange-dark
outline-orange-light

Buttons fix: disabled states

---

.changeset/healthy-beds-count.md
icon-registry/icons-static/chevron-left-large_x24.svg
icon-registry/icons-static/chevron-left-large_x8.svg
icon-registry/icons-static/chevron-left-medium_x16.svg
icon-registry/icons-static/chevron-left-medium_x24.svg
icon-registry/icons-static/chevron-left-small_x24.svg
icon-registry/icons-static/chevron-right-large_x24.svg
icon-registry/icons-static/chevron-right-large_x8.svg
icon-registry/icons-static/chevron-right-medium_x16.svg
icon-registry/icons-static/chevron-right-medium_x24.svg
icon-registry/icons-static/chevron-right-small_x24.svg
package.json

Originally motivated by needing the right-chevron for [this comp](https://www.figma.com/design/XYBgOykHfLCi1yT4Va7GLO/Test-generation?node-id=3150-137694&t=86v1kwsYgEjakhG3-1) for Studio.
I went ahead and added all sizes and types for all of the chevron left and right icons. So all icons here are in the design-system: https://www.figma.com/design/1WJ3GVQyMV5e7xVxPg3yID/Design-System?m=auto&node-id=6814-10841&t=GrG6iztKgxoEMunp-1

feat: add chevron-right and chevron-left icons for small, medium, and large for all sizes

---

.changeset/yummy-pillows-lose.md
components/Button/constants/src/index.ts

Added variants for `teal` and `jade` outline buttons

---

.changeset/hip-dragons-cough.md
components/Tag/ReadMe.md
components/Tag/constants/src/index.ts
components/Tag/react/Tag.tsx
components/Tag/react/TagReact.cy.tsx
components/Tag/vue/Tag.vue
components/Tag/vue/TagVue.cy.tsx

Adding tag, gray900
